python train_strivec.py --config configs/surrey/dan.txt --recon_frame 49 --expname frame_49
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 48 --expname frame_48
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 47 --expname frame_47
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 46 --expname frame_46
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 45 --expname frame_45
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 44 --expname frame_44
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 43 --expname frame_43
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 42 --expname frame_42
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 41 --expname frame_41
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 40 --expname frame_40
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 39 --expname frame_39
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 38 --expname frame_38
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 37 --expname frame_37
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 36 --expname frame_36
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 35 --expname frame_35
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 34 --expname frame_34
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 33 --expname frame_33
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 32 --expname frame_32
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 31 --expname frame_31
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 30 --expname frame_30
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 29 --expname frame_29
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 28 --expname frame_28
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 27 --expname frame_27
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 26 --expname frame_26
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 25 --expname frame_25
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 24 --expname frame_24
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 23 --expname frame_23
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 22 --expname frame_22
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 21 --expname frame_21
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 20 --expname frame_20
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 19 --expname frame_19
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 18 --expname frame_18
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 17 --expname frame_17
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 16 --expname frame_16
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 15 --expname frame_15
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 14 --expname frame_14
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 13 --expname frame_13
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 12 --expname frame_12
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 11 --expname frame_11
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 10 --expname frame_10
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 9 --expname frame_9
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 8 --expname frame_8
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 7 --expname frame_7
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 6 --expname frame_6
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 5 --expname frame_5
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 4 --expname frame_4
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 3 --expname frame_3
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 2 --expname frame_2
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 1 --expname frame_1
python train_strivec.py --config configs/surrey/dan.txt --recon_frame 0 --expname frame_0
